name: Deploy documentation
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: mattnotmitt/doxygen-action@v1
        with:
          doxyfile-path: "./Doxyfile"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
